const inputsSignUp = [
  {
    id: 1,
    name: "firstName",
    type: "text",
    required: true,
    autocomplete: "off",
    label: "имя",
    // placeholder: "email",
    minlength: 5,
    maxlength: 25,
  },
  {
    id: 2,
    name: "lastName",
    type: "text",
    required: true,
    autocomplete: "off",
    label: "фамилия",
    // placeholder: "Мухин",
    minlength: 6,
    maxlength: 20,
  },
  {
    id: 3,
    name: "middleName",
    type: "text",
    autocomplete: "off",
    label: "отчество",
    // placeholder: "Витальевич",
    minlength: 2,
    maxlength: 20,
  },
  {
    id: 4,
    name: "email",
    type: "email",
    required: true,
    autocomplete: "off",
    label: "эл. почтовый ящик",
    // placeholder: "Мухин",
    minlength: 6,
    maxlength: 40,
  },
  {
    id: 5,
    name: "password",
    type: "password",
    required: true,
    autocomplete: "off",
    label: "пароль",
    // placeholder: "Мухин",
    minlength: 6,
    maxlength: 20,
  },
]

export default inputsSignUp
